# docker-compose.yml
version: "3"
services:
  app:
    container_name: 78Station
    image: 78station
    env_file: .env
    restart: on-failure
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    build: .
    depends_on:
      - postgres
      - nginx
    ports:
      - "5001:5001"

  nginx:
    container_name: 78-Nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  postgres:
    container_name: 78-Database
    image: postgres:11-alpine
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 35s
      interval: 30s
      retries: 3
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    volumes:
      - ${PWD}/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=batatao53421
      - POSTGRES_DB=78Station