const MODE_BRIDGE = require('../bridge').MODE_BRIDGE
const Logger = require('./logger')
let logger
if (MODE_BRIDGE) {
    logger = new Logger(require('../bridge').P.name)
} else {
    logger = new Logger('app')
}

const db = require('./database')
const fm = require('./fileManager')
if (MODE_BRIDGE) DEFAULT_BOARDS = require('../bridge').DEFAULT_BOARDS
else DEFAULT_BOARDS = require('../app').DEFAULT_BOARDS

const tables = {
    BOARD : 'board'
}
const schema = {
    BOARD : 'board',
}

exports.schema = schema
exports.tables = tables

async function checkTableExists(table) {
    try {
        let q = await db.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE  table_schema = 'public'
                AND    table_name   = '${table}'
            );
        `)
        return (q[0] && q[0].exists === true)

    } catch (err) { 
        logger.error('Error after check table')
    }
    return false
}

exports.init = async(callback) => {
    if (await checkTableExists(tables.BOARD) === false) {
        try {
            await db.query(`
                CREATE TABLE ${tables.BOARD} (
                    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(200) NOT NULL,
                    path varchar(100) NOT NULL,
                    date timestamp DEFAULT current_timestamp
                );
            `)
            logger.ok('Table: board, successful created!')
        } catch (err) {
            logger.fatal('Error after create \'board\' table', err)
        }

        try {
            await db.query(`CREATE SCHEMA IF NOT EXISTS ${schema.BOARD}`)
            await db.query(`CREATE SCHEMA IF NOT EXISTS public`)

        } catch (err) {
            logger.fatal('Error after create boards schema')
        }
    }

    try {
        for (b of DEFAULT_BOARDS) {
            let q = await db.query(`SELECT path FROM ${tables.BOARD} WHERE path = $1`, [b.path])
            if (!q[0] || !q[0].path) {
                await db.query(`INSERT INTO ${tables.BOARD}(name, path) VALUES ($1, $2)`, [b.name, b.path])
                await db.query(`
                    CREATE TABLE ${schema.BOARD}.${b.path} (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        uid varchar(200) NOT NULL,
                        username varchar(200) DEFAULT('Anonymous'),
                        content text DEFAULT(''),
                        file_info text DEFAULT(''),
                        password varchar(200) DEFAULT(''),
                        mentions text DEFAULT('[]'),
                        date timestamp DEFAULT current_timestamp
                    );
                `)
            }
        }
    } catch (err) {
        logger.fatal('Error after insert default boards', err)
    }

    fm.updateFileSystem(tables.BOARD)
    if (callback) callback()
}